[project]
name = "hbhelper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.7",
    "pandas>=2.2.3",
]

[tool.uv]
package = true

[dependency-groups]
dev = [
    "pandas-stubs>=3.0.0.260204",
]

[project.scripts]
hbhelper = "hbhelper.cli:cli"
